### ISSUE TITLE
Bots are not prevented from standing in other bots' bases

### ISSUE THREAD

**Issue by devLotto** [Etimo/diamonds#78]
Currently during the competition, a competitor is running a bot 24/7 with the objective of walking into the base of any bot that reaches 150 points. This has the effect that the affected bot cannot return diamonds to their spawn, and thus locking them to forever stay at 150 points.

This kind of griefing and abuse of the mechanics defeats the purpose of the competition and makes it virtually impossible to claim any sort of higher place in the highscores if you enter the competition at this stage.

**Comment by teozkr** [comment]
Hey,

It should be impossible to stand in another player's base:

https://github.com/Etimo/diamonds/blob/7857df7ee22831514c0b54e6cceda41952f9ceeb/diamonds-api/Diamonds.GameEngine/MoveService.cs#L143-L148

If they are able to do that then it is a bug, and should be reported.

Standing *around* the base is considered legal (for now), since there are counterplay strategies. The highscore table also seems to have moved a fair emount since you filed the issue (as you have probably noticed :P), so I'm not too concerned yet about it preventing others from competing. We'll definitely keep an eye on how the situation evolves, though.

**Comment by GustavPS** [comment]
It is possible to stand in other peoples bases, "All your base is belong to us" is doing it all the time (he has been online for ~5 hours), as soon as someone connects he stands in their bases, except if it's "Etimo 1" or "Etimo 2"

**Comment by teozkr** [comment]
Oh, I see. I didn't see AYB do anything before, but I guess that was because it ignores our bots. I can see it harassing @devLotto now. I'll look into the issue.

**Comment by devLotto** [comment]
If you didn't look into it already: from a quick peek in MoveService.cs, I'm guessing this is the offending line: https://github.com/Etimo/diamonds/blob/7857df7ee22831514c0b54e6cceda41952f9ceeb/diamonds-api/Diamonds.GameEngine/MoveService.cs#L159 

``b.Position`` should probably be ```b.Base```. Easy to miss if that's it! 😃

**Comment by teozkr** [comment]
Yeah, probably. Just setting up a test case to make sure.

**Comment by teozkr** [comment]
Alright, the fix should be deployed now. Sorry about the delay and the dismissive tone in my first reply.
